In [1]:
import numpy as np
import math

In [5]:
a=np.array([1,2,3])#define np array
print(a)
print(a.ndim)#print dimension of array a
a.shape

[1 2 3]
1


(3,)

In [6]:
a.dtype

dtype('int32')

In [10]:
d=np.zeros((2,3))
print(d)
e=np.ones((2,3))
print(e)
r=np.random.rand(2,3)
r

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


array([[0.70956537, 0.15068367, 0.02545181],
       [0.96658606, 0.29744526, 0.06845657]])

In [13]:
f=np.arange(10,50,2)
f

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [16]:
t=np.linspace(0,2,15)
t

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        , 1.14285714, 1.28571429,
       1.42857143, 1.57142857, 1.71428571, 1.85714286, 2.        ])

# Array opertaions

In [17]:
#we can do all arithmatic operations on array.
farenheit=np.array([0,-10,-5,-15,0])
celcius=(farenheit-31)*(5/9)
celcius
celcius>-20

array([ True, False, False, False,  True])

In [18]:
celcius%2==0

array([False, False,  True, False, False])

In [19]:
print(f.mean(),f.max(),f.min(),f.sum())

29.0 48 10 580


In [20]:
#we can also convert images to numpy array


# regex

In [21]:
import re
text='this is a good day'
if re.search('good',text):
    print('found')
else:
    print('Alas')

found


In [25]:
text='any ashakshjksdhk any DASACAC any 12545521'
print(re.split('any',text))
print(re.findall('any',text))

['', ' ashakshjksdhk ', ' DASACAC ', ' 12545521']
['any', 'any', 'any']


In [26]:
re.search('any',text)

<re.Match object; span=(0, 3), match='any'>

In [27]:
#match() function returns boolean values.
grades="ACAAAABCBCBAA"
re.findall('B',grades)

['B', 'B', 'B']

In [28]:
re.findall('[AB]',grades)

['A', 'A', 'A', 'A', 'A', 'B', 'B', 'B', 'A', 'A']

In [29]:
re.findall('[A][B-C]',grades)

['AC', 'AB']

In [30]:
re.findall('AB|AC',grades)

['AC', 'AB']

In [31]:
re.findall('[^A]',grades)#it will print except 'A'

['C', 'B', 'C', 'B', 'C', 'B']

In [32]:
re.findall("A{2,10}",grades)

['AAAA', 'AA']

In [33]:
re.findall('[\w]*\[edit\]',grades)# find all the character followed by 'edit' keyword

[]

In [34]:
for item in re.finditer("([\w]*)(\[edit\])",grades):
    print(item.group())

In [36]:
# for more details see python docs for regex
#the verbose mode allows us to write multiline regex and increases readability
#having base skill of regular expresssion is core skill of data science
